version: "3.5"
services:
        gateway: # stefan
                image: nginx
                volumes:
                        - "./gateway/nginx:/etc/nginx"
                        - "./user_frontend/dist:/usr/share/nginx/html/frontend/dist"
                        - "./user_frontend/index.html:/usr/share/nginx/html/frontend/index.html"
                ports:
                        - "6969:80"
#        vehicle-location: # stefan
#                image: python
#                volumes:
#                        - "./vehicle:/code"
#                command: "python /code/main.py"
#        agent-backend: # stefan
#                build: "./agent_backend/"
#                command: python /code/manage.py runserver 0.0.0.0:8000
#                volumes:
#                  - "./agent_backend/:/code/"
#        agent-database: # stefan
#                image: postgres
 #       message-queue: # stefan
 #               image: rmohr/activemq
 #               ports:
 #                       - "665:8161"
 #       email-service: # stefan
 #               image: maven
 #               command: cd /usr/src/mymaven && mvn spring-boot:run
 #               volumes:
 #                       - "./email_service/:/usr/src/mymaven/"

        message-service: # stefan
                image: maven
                command: /usr/src/mymaven/run.sh
                volumes:
                        - "./message_service/:/usr/src/mymaven/"
        order-service: # borislav
                image: maven
                command: /usr/src/mymaven/run.sh
                volumes:
                        - "./order_handling_service/:/usr/src/mymaven/"
        user-service: # uros
                image: maven
                command: /usr/src/mymaven/run.sh
                volumes:
                        - "./user_service/:/usr/src/mymaven/"
        database: # stefan
                environment:
                        - POSTGRES_PASSWORD=admin
                image: postgres
        db_setup: # stefan
                volumes:
                        - "./setup/:/opt/code"
                command: /opt/code/setup.sh
                image: postgres
                links:
                        - database
        admin-service: # uros
                image: maven
                command: /usr/src/mymaven/run.sh
                volumes:
                        - "./admin_service/:/usr/src/mymaven/"
        vehicle-service: # stefan
                image: maven
                command: /usr/src/mymaven/run.sh
                volumes:
                        - "./vehicle_service/:/usr/src/mymaven/"
        pgadmin: #uros
                restart: always
                image: dpage/pgadmin4
                ports:
                    - "8000:80"
                environment:
                    PGADMIN_DEFAULT_EMAIL: admin@admin.com
                    PGADMIN_DEFAULT_PASSWORD: admin
